### ISSUE TITLE
version locking seems to ignore COMMIT-ISH SHA

### ISSUE THREAD

**Issue by mroth** [jingweno/nut#16]
For example, as a test, I put the following in my `Nut.toml`

```
[dependencies]
"github.com/spf13/pflag" = "6bdb0b3748b247a8c28532fcd78b60c1a7ec07db"
```

That being the full SHA for the oldest commit in that repository.

When running `nut install`, the _output makes it appear_ to be getting the correct version:

```
$ nut install  
Downloading github.com/spf13/pflag@6bdb0b3748b247a8c28532fcd78b60c1a7ec07db
```

**However,** the most recent version is actually retrieved and vendored instead.  I tested this by comparing the files manually, and the most recent changes were there.

**Comment by owenthereal** [comment]
This is definitely not desired. I'll need to look into it. It should [`git-clone` and `git-checkout`](https://github.com/jingweno/nut/blob/master/install.go#L28) to specified versions.

**Comment by owenthereal** [comment]
Please see https://github.com/jingweno/nut/pull/18 for the fix
