### ISSUE TITLE
installation fails on existing project

### ISSUE THREAD

**Issue by technoweenie** [jingweno/nut#24]
I'm trying to use Nut with Git LFS. All I did was take the current master, add the toml file, and move the `.vendor/src` path to `vendor/_nuts`.

``` command
$ nut install
Downloading github.com/technoweenie/go-contentaddressable@38171def3cd15e3b76eb156219b3d48704643899
Downloading github.com/kr/pty@5cf931ef8f76dccd0910001d74a58a7fca84a83d
Downloading github.com/spf13/cobra@864687ae689edc28688c67edef47e3d2ad651a1b
Downloading github.com/rubyist/tracerx@f6aa9369b3277bc21384878e8279642da722f407
Downloading github.com/cheggaaa/pb@bd14546a551971ae7f460e6d6e527c5b56cd38d7
Downloading github.com/kr/text@6807e777504f54ad073ecef66747de158294b639
Downloading github.com/olekukonko/ts@ecf753e7c962639ab5a1fb46f7da627d4c0a04b8
Downloading github.com/spf13/pflag@463bdc838f2b35e9307e91d480878bda5fff7232
Downloading github.com/bmizerany/assert@e17e99893cb6509f428e1728281c2ad60a6b31e3
Downloading github.com/kr/pretty@088c856450c08c03eb32f7a6c221e6eefaa10e6f
Vendoring dependencies
package assert: unrecognized import path "assert"
exit status 1
```

Here's my toml file:

``` toml
[application]

name = "git-lfs"
version = "0.5.1"
authors = [
  "Rick Olson <technoweenie@gmail.com>",
]

[dependencies]

"github.com/bmizerany/assert"                   = "e17e99893cb6509f428e1728281c2ad60a6b31e3"
"github.com/cheggaaa/pb"                        = "bd14546a551971ae7f460e6d6e527c5b56cd38d7"
"github.com/kr/pretty"                          = "088c856450c08c03eb32f7a6c221e6eefaa10e6f"
"github.com/kr/pty"                             = "5cf931ef8f76dccd0910001d74a58a7fca84a83d"
"github.com/kr/text"                            = "6807e777504f54ad073ecef66747de158294b639"
"github.com/olekukonko/ts"                      = "ecf753e7c962639ab5a1fb46f7da627d4c0a04b8"
"github.com/spf13/cobra"                        = "864687ae689edc28688c67edef47e3d2ad651a1b"
"github.com/spf13/pflag"                        = "463bdc838f2b35e9307e91d480878bda5fff7232"
"github.com/technoweenie/go-contentaddressable" = "38171def3cd15e3b76eb156219b3d48704643899"
"github.com/rubyist/tracerx"                    = "f6aa9369b3277bc21384878e8279642da722f407"
```

Do I have to rewrite all the import paths myself? I thought Nut was supposed to handle that for me.

EDIT: Git LFS PR: https://github.com/github/git-lfs/pull/331

**Comment by technoweenie** [comment]
I fixed a plain "assert" import in https://github.com/github/git-lfs/commit/ac2d1f22dcb21e5e6ec0d804a4772a824c400265, but it doesn't seem to solve the issue.

**Comment by technoweenie** [comment]
Ah, I had to fork that repo and fix it _there_.

**Comment by owenthereal** [comment]
> Do I have to rewrite all the import paths myself? I thought Nut was supposed to handle that for me.

Yup, `nut` is supposed to rewrite the import paths. The error is because `nut` runs `go get` after downloading a particular revision of the repo, and as you pointed out, the `example` package doesn't even build...maybe I should skip packages that can't be built instead of failing the whole process.

Please also note that `nut` will be changed to comply with the [vendor-spec](https://github.com/kardianos/vendor-spec) in the near future once it's firmed, e.g., dependencies will live in the internal folder, a `vendor.json` will be generated (similar to `Gemfile.lock`). Related [discussions](https://groups.google.com/forum/#!topic/golang-dev/nMWoEAG55v8%5B1-25%5D).

**Comment by technoweenie** [comment]
The package technically builds because the file is an example file that's not really referenced by anything else in the package. At the least, there should be an error message letting me know what file or even package is causing the problem.

I've been following the discussion on golang-nuts and hoping for a community solution like vendor-spec. :+1:

**Comment by owenthereal** [comment]
> At the least, there should be an error message letting me know what file or even package is causing the problem.

:+1:. I'll add that when I get a chance.

**Comment by ebramanti** [comment]
Any update on this? I'm getting `assert` errors whenever I run `nut install`
