### ISSUE TITLE
Readme nitpick?

### ISSUE THREAD

**Issue by kpublik** [jingweno/nut#4]
First, congrats on the placing in the Gopher Gala contest.

Ok, so this is just nitpicking about your _readme_, but:
- Nuts are not part of a Gopher's natural diet.
- The image shown is a chipmunk, not a gopher.

Maybe you didn't know, or don't care, or maybe it's just a joke that's lost on me.

Again, congrats on the contest.

**Comment by owenthereal** [comment]
@kpublik I didn't know much about Gopher's diet but a quick search says [it eats nuts](http://www.victorpest.com/advice/rodent-library/gophers#diet). The image may not be a Gopher, but hey, tips to win a hackathon - putting a cute image on the README :beers:! Again, thanks for the interests in the project!
