### ISSUE TITLE
nut rewrite rules use absolute paths?

### ISSUE THREAD

**Issue by sean-** [jingweno/nut#9]
Hello.  I'm trying to put together a sample build example using nut and am having problems with nut "just working."  The two issues that I have are that `nut` is rewriting the imported `spf13/cobra`'s vendor dependencies using the absolute path.

``` sh
% env | grep GO
GOPATH=/Users/sean-/go
% pwd
/private/tmp/t/test
% ll
total 32
-rw-r--r--  1 sean-  wheel    5 Feb 21 15:02 .gitignore
-rw-r--r--  1 sean-  wheel  134 Feb 21 15:03 Nut.toml
-rw-r--r--  1 sean-  wheel   40 Feb 21 15:02 README.md
-rw-r--r--  1 sean-  wheel  318 Feb 21 15:08 main.go
% go build
main.go:5:2: open /private/tmp/t/test/vendor/_nuts/github.com/spf13/cobra: no such file or directory
Exit 1
% nut install
Downloading github.com/spf13/cobra@latest
Vendoring dependencies
% ll
total 32
-rw-r--r--  1 sean-  wheel    5 Feb 21 15:02 .gitignore
-rw-r--r--  1 sean-  wheel  134 Feb 21 15:03 Nut.toml
-rw-r--r--  1 sean-  wheel   40 Feb 21 15:02 README.md
-rw-r--r--  1 sean-  wheel  318 Feb 21 15:08 main.go
drwxr-xr-x  3 sean-  wheel  102 Feb 21 15:09 vendor/
% go build
vendor/_nuts/github.com/spf13/cobra/command.go:25:2: cannot find package "_/private/tmp/t/test/vendor/_nuts/github.com/spf13/pflag" in any of:
    /opt/local/go/src/_/private/tmp/t/test/vendor/_nuts/github.com/spf13/pflag (from $GOROOT)
    /Users/sean-/go/src/_/private/tmp/t/test/vendor/_nuts/github.com/spf13/pflag (from $GOPATH)
Exit 1
```

The `Nut.toml` file I'm using is:

``` ini
[application]
name = "test"
version = "0.0.1"
authors = ["Your Name <you@example.com>"]

[dependencies]
"github.com/spf13/cobra" = ""
```

And the `main.go` sample file:

``` go
package main

import (
    "fmt"
    "os"
    "path/filepath"

    "./vendor/_nuts/github.com/spf13/cobra"
)

var RootCmd = &cobra.Command{
    Use:   filepath.Base(os.Args[0]),
    Short: "short description",
    Long:  "long description",
    Run: func(cmd *cobra.Command, args []string) {
        fmt.Println("Hello Gophers!")
    },
}

func main() {
    RootCmd.Execute()
}
```

The import command in the incorrectly rewritten vendored file is `vendor/_nuts/github.com/spf13/cobra/command.go`:

``` go
// vendor/_nuts/github.com/spf13/cobra/command.go
package cobra
import (
        "bytes"
        "fmt"
        "io"
        "os"
        "strings"

        flag "_/private/tmp/t/test/vendor/_nuts/github.com/spf13/pflag"
)
```

I would expect that to use a relative path and be resolved using a relative path to the directory in question.  Something like:

``` go
// vendor/_nuts/github.com/spf13/cobra/command.go
package cobra

import (
        "bytes"
        "fmt"
        "io"
        "os"
        "strings"

        flag "../pflag"
)
```

Works as expected:

``` sh
% go build
% ./test
Hello Gophers!
```

Is there something I'm doing wrong in my usage?

**Comment by owenthereal** [comment]
> flag "_/private/tmp/t/test/vendor/_nuts/github.com/spf13/pflag"

There is a bug. I'd need to look into why this import is special. You're doing all things correctly.

**Comment by sean-** [comment]
Whew. Hopefully the repro steps work for you. If you have any problems let me know.

## 

Sean Chittenden

**Comment by owenthereal** [comment]
I was able to get the right import path for the file `vendor/_nuts/github.com/spf13/cobra/command.go`:

``` go
package cobra

import (
    "bytes"
    "fmt"
    "io"
    "os"
    "strings"

    flag "github.com/jingweno/test/vendor/_nuts/github.com/spf13/pflag"
)
```

After carefully reading your code, the problem comes from your `main.go`:

``` go
import (
    "fmt"
    "os"
    "path/filepath"

    "./vendor/_nuts/github.com/spf13/cobra"
)
```

Your import path of `cobra` is wrong. It should be the full import path related to your `GOPATH`, e.g., `github.com/jingweno/test/vendor/_nuts/github.com/spf13/cobra` in my case.

**Comment by sean-** [comment]
AH HA!  I missed that in my understanding of how I could use this.  I was hoping that I could use a path that was outside of my GOPATH for maintaining the source of a project.  For example, if `GOPATH=${HOME}/go` but a project was being built in `~/src/myorg-foo` things would "just work" but that's not the case.  Instead `foo` needs to be moved in to `${GOPATH}/src/github.myorg.com/myorg/foo`.  Which mechanically makes sense, but I was hoping to avoid because the path is huge (`echo -n my/import/path | wc -c => 100`).  Regardless, thanks for the clarification, `nut` is working as expected now.

**Comment by owenthereal** [comment]
> For example, if GOPATH=${HOME}/go but a project was being built in ~/src/myorg-foo things would "just work" but that's not the case.

Unfortunately not. Go actually looks into your `GOPATH` when compiling. 

> Which mechanically makes sense, but I was hoping to avoid because the path is huge 

You could put your `GOPATH` into `CDPATH` so that `cd` can be shorter.

**Comment by sean-** [comment]
True, though my main concern was actually in forking code internally and needing to rewrite the import paths every time.  The length of the path is a concern and certainly the first thing that came to mind, but once someone forks code, they are going to need to rewrite large chunks of code to match the forked path, otherwise they will be importing the parent fork's code and libraries, not the version I'm iterating on.  Unless I'm missing something.  ?
